from . import pivotino_res_company
from . import pivotino_crm_stage
from . import pivotino_crm_lead
from . import pivotino_sale_order
from . import pivotino_crm_sale
from . import pivotino_crm_lost_reason_category
from . import pivotino_sale_target
from . import pivotion_crm_stage_duration
from . import pivotino_mail_activity
